Completed prep-javascript-functions exercise.
matthewkhu/javascript-prep-0124-code-solutions pull request #8
Opened 2024-01-16 06:19 UTC by matthewkhu

![image](https://github.com/matthewkhu/javascript-prep-0124-code-solutions/assets/154471303/0e9b4cbe-4aab-483e-81ea-2d501f73017b)

2024-01-16 18:41 UTC, Zhiwutian requested changes
Great work! Just one tiny update on casing!

2024-01-16 18:41 UTC, BrettAlbright commented on prep-javascript-functions/main.js
> +const Juan = getFullName('Juan', 'Ramirez');
This variable should be lowercased
juan instead of Juan
as variables that start with capital letters are typically used for Classes and Constructor functions in JavaScript

2024-01-16 21:36 UTC, matthewkhu commented
![Screenshot 2024-01-16 at 1 32 57 PM](https://github.com/matthewkhu/javascript-prep-0124-code-solutions/assets/154471303/5250e4f0-53c0-4df1-aed3-d219585f9cef)

2024-01-17 00:06 UTC, Zhiwutian approved these changes
👍🏼

2024-01-17 18:44 UTC, merged